Pages/Contact.cshtml.cs
using Servindustria.Models;
using Servindustria.Data.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using System.Globalization;

public class ContactModel : PageModel {
    private readonly IAdminCallRequestRepository _callRequestRepository;
    private readonly IAdminContactFormRepository _contactFormRepository;

    public ContactModel(IAdminCallRequestRepository callRequestRepository, IAdminContactFormRepository contactFormRepository) {
        _callRequestRepository = callRequestRepository;
        _contactFormRepository = contactFormRepository;
    }

    [FromForm]
    public AdminCallRequest? AdminCallRequest { get; set; }

    [FromForm]
    public AdminContactForm? ContactForm { get; set; }

    public async Task<IActionResult> OnPostAdminCallRequestAsync() {
        if (AdminCallRequest == null) return new JsonResult(new {success = false, error = "Unknown Error"});

        int phoneLength = Math.Abs(AdminCallRequest.Phone).ToString().Length;
            if (phoneLength != 9 && phoneLength != 0)
                return new JsonResult(new {success = false, error = "O número de telefone / telemóvel deve ter 9 dígitos"});

        await _callRequestRepository.AddAdminCallRequestAsync(AdminCallRequest);
        return new JsonResult(new {success = true});
    }

    public async Task<IActionResult> OnPostAdminContactFormAsync() {
        if (ContactForm == null) return new JsonResult(new {success = false, error = "Unknown Error"});

        
        if (ContactForm.Phone == null) ContactForm.Phone = 0;
        int phoneLength = Math.Abs(ContactForm.Phone.Value).ToString().Length;
            if (phoneLength != 9 && phoneLength != 0 && ContactForm.Phone != 0)
                return new JsonResult(new {success = false, error = "O número de telefone / telemóvel deve ter 9 dígitos"});
        
        if (!IsValidEmail(ContactForm.Email)) return new JsonResult(new {success = false, error = "O email não é válido"});

        await _contactFormRepository.AddAdminContactFormAsync(ContactForm);
        return new JsonResult(new {success = true});
    }


    private bool IsValidEmail(string email) {
        if (string.IsNullOrWhiteSpace(email)) return false;

        try {
            email = Regex.Replace(email, @"(@)(.+)$", DomainMapper, RegexOptions.None, TimeSpan.FromMilliseconds(200));

            string DomainMapper(Match match) {
                var idn = new IdnMapping();
                string domainName = idn.GetAscii(match.Groups[2].Value);
                return match.Groups[1].Value + domainName;
            }
        } catch (RegexMatchTimeoutException) {
            return false;
        } catch (ArgumentException) {
            return false;
        }

        try {
            return Regex.IsMatch(email,
                @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
                RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(250));
        } catch (RegexMatchTimeoutException) {
            return false;
        }
    }
}

Pages/LoginRegister.cshtml.cs
using Servindustria.Models;
using Servindustria.Data.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using System.Globalization;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

public class LoginRegisterModel : PageModel {
    private readonly IUserRepository _repository;

    /* REGISTER */
    [FromForm]
    public User? NewUser { get; set; }
    
    [BindProperty]
    public string? ConfirmPassword { get; set; }

    /* LOGIN */
    [BindProperty]
    public string? loginEmail { get; set; }
    
    [BindProperty]
    public string? loginPassword { get; set; }

    public LoginRegisterModel(IUserRepository repository) {
        _repository = repository;
    }

    public async Task<IActionResult> OnPostLoginAsync() {
        if (loginEmail == null || loginPassword == null) return new JsonResult(new {success = false, error = "Unknown Error"});

        if (await _repository.LoginAsync(loginEmail, loginPassword)) {
            var Claims = new List<Claim> {
                        new Claim(ClaimTypes.Name, loginEmail),
                        new Claim(ClaimTypes.Role, await _repository.IsAdmin(loginEmail) ? "Admin" : "User")
                    };
            await HttpContext.SignInAsync("AuthCookies", new ClaimsPrincipal(new ClaimsIdentity(Claims, "AuthCookies")));
        
            return new JsonResult(new {success = true});
        } else {
            return new JsonResult(new {success = false, error = "Invalid credentials"});
        }
    }

    public async Task<IActionResult> OnPostRegisterAsync() {
        if (NewUser == null) return new JsonResult(new {success = false, error = "Unknown Error"});

        if (await _repository.EmailExistsAsync(NewUser.Email)) ModelState.AddModelError("Email", "Já existe um utilizador com este email");
        if (await _repository.NifExistsAsync(NewUser.Nif)) ModelState.AddModelError("Nif", "Já existe um utilizador com este NIF");
        
        if (!IsValidEmail(NewUser.Email)) ModelState.AddModelError("Email", "O email não é válido");
        if (NewUser.Password != ConfirmPassword) ModelState.AddModelError("Password", "As passwords não coincidem");
        int nifLength = Math.Abs(NewUser.Nif).ToString().Length;
            if (nifLength != 9 && nifLength != 0) ModelState.AddModelError("Nif", "O NIF deve ter 9 dígitos");
        int phoneLength = Math.Abs(NewUser.Phone).ToString().Length;
            if (phoneLength != 9 && phoneLength != 0) ModelState.AddModelError("Phone", "O número de telefone / telemóvel deve ter 9 dígitos");

        var modelErrors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
        if (modelErrors.Count > 0) return new JsonResult(new {success = false, errors = modelErrors});

        var Claims = new List<Claim> {
            new Claim(ClaimTypes.Name, NewUser.Email),
            new Claim(ClaimTypes.Role, await _repository.IsAdmin(NewUser.Email) ? "Admin" : "User")
        };
        await HttpContext.SignInAsync("AuthCookies", new ClaimsPrincipal(new ClaimsIdentity(Claims, "AuthCookies")));
        
        NewUser.Password = BCrypt.Net.BCrypt.HashPassword(NewUser.Password);

        await _repository.AddUserAsync(NewUser);
        return new JsonResult(new {success = true});        
    }

    private bool IsValidEmail(string email) {
        if (string.IsNullOrWhiteSpace(email)) return false;

        try {
            email = Regex.Replace(email, @"(@)(.+)$", DomainMapper, RegexOptions.None, TimeSpan.FromMilliseconds(200));

            string DomainMapper(Match match) {
                var idn = new IdnMapping();
                string domainName = idn.GetAscii(match.Groups[2].Value);
                return match.Groups[1].Value + domainName;
            }
        } catch (RegexMatchTimeoutException) {
            return false;
        } catch (ArgumentException) {
            return false;
        }

        try {
            return Regex.IsMatch(email,
                @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
                RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(250));
        } catch (RegexMatchTimeoutException) {
            return false;
        }
    }
    public async Task<IActionResult> OnPostLogout() {
        await HttpContext.SignOutAsync("AuthCookies");
        return RedirectToPage("/Index");
    }
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

@{ 
    string currentPage = String.Empty;
    if (Context != null && Context.Request != null && Context.Request.Path != null)
        { currentPage = Context.Request.Path; }
    
    bool isAdmin = User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("Admin");
}

@* Get Previous Page Name *@
@{
    var referrer = "";
    if (Context != null && Context.Request != null && Context.Request.Headers != null)
        referrer = Context.Request.Headers["Referer"].ToString();
    string previousPageName = "";

    if (!string.IsNullOrEmpty(referrer))
    {
        var uri = new Uri(referrer);
        previousPageName = System.IO.Path.GetFileNameWithoutExtension(uri.LocalPath);
    }
}

<html>
    <head>
        <title>Servindustria</title>
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true">
        <link rel="shortcut icon" type="image/x-icon" href="~/imgs/favicon.png">
    </head>

    <body>
        <header>
            @if (!currentPage.EndsWith("/")) {
                <div class="companyName @(previousPageName == "" ? "fromIndex" : "")">
                    <p>Servindustria</p>
                </div>
            }
            <ul>
                <li class="@(currentPage.EndsWith("/") ? "currentPage" : "exit-trigger")">
                    <a asp-page="Index">Página Inicial</a>
                </li>

                @if (isAdmin) {
                    @Html.AntiForgeryToken()
                    <script src="~/js/admin.js" asp-append-version="true"></script>
                    <li class="@(currentPage.EndsWith("/admin/pedidosChamada") ? "currentPage" : "exit-trigger")">
                        <div id="notificationCallRequests" class="notification">
                            <img src="~/imgs/notification.png" alt="Notificação"/>
                        </div>
                        <a asp-page="AdminCallRequests">Pedidos de Chamada</a>
                    </li>
                    <li class="@(currentPage.EndsWith("/admin/pedidosContacto") ? "currentPage" : "exit-trigger")">
                        <div id="notificationContactForms" class="notification">
                            <img src="~/imgs/notification.png" alt="Notificação"/>
                        </div>
                        <a asp-page="AdminContactForms">Pedidos de Contacto</a>
                    </li>
                <li class="@(currentPage.EndsWith("/admin/gerirItems") ? "currentPage" : "exit-trigger")">
                    <a asp-page="AdminManageItems">Gerir Items</a>
                </li>
                } else {
                    <li class="@(currentPage.EndsWith("/produtos") ? "currentPage" : "exit-trigger")">
                        <a asp-page="Products">Produtos</a>
                    </li>
                    <li class="@(currentPage.EndsWith("/tabelasTecnicas") ? "currentPage" : "exit-trigger")">
                        <a asp-page="TechnicalTablesAndCatalogs">Tabelas Técnicas / Catálogos</a>
                    </li>
                    <li class="@(currentPage.EndsWith("/contacto") ? "currentPage" : "exit-trigger")">
                        <a asp-page="Contact">Contacto</a>
                    </li>  
                }
                
                @if (User.Identity != null && User.Identity.IsAuthenticated) {
                    <li class="exit-trigger">
                        <form id="logout-form" method="post" asp-page="/Authentication" asp-page-handler="Logout">
                            @Html.AntiForgeryToken()
                            <a href="#" id="logout-button">Logout</a>
                        </form>
                    </li>
                    <script src="~/js/logout.js" asp-append-version="true"></script>
                } else {
                    <li class="@(currentPage.EndsWith("/autenticacao") ? "currentPage" : "exit-trigger")">
                        <a asp-page="Authentication">Login / Registar</a>
                    </li>
                }
            </ul>
        </header>
        
        @if (!isAdmin) {
            <div id="movableContainer" style="@(!currentPage.EndsWith("/") ? "transform: translate(50px, 150px);" : "")">
                <img src="~/imgs/phone.png" alt="Ligue-me" id="movablePhone"/>

                <div id="popupBox">
                    <p>Quer ser contactado?</p>
                    <p>Digite o seu número!</p>
                    <div id="callRequest-error" class="error"></div>
                    <div id="callRequest-success" class="success"></div>
                    <form id="callRequest-form" class="formClass" method="post" asp-page="/Contact" asp-page-handler="AdminCallRequest">
                        @Html.AntiForgeryToken()
                        <input type="text" name="Name" placeholder="Nome" required/>
                        <input type="text" name="Company" placeholder="Empresa (opcional)"/>
                        <input type="number" name="Phone" placeholder="Nº Telefone / Telemóvel" required/>
                        <input type="text" name="Message" placeholder="Observações (opcional)" />
                        <input type="submit" value="Ligar-me"/>
                    </form>
                </div>
            </div>
        }

        <main>
            @RenderBody()
        </main>

        <footer>
            <p>
                &copy; 2024 - Servindustria
            </p>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="~/js/main.js" asp-append-version="true"></script>
        @if (!isAdmin) {
            <script src="~/js/movableIcon.js" asp-append-version="true"></script>
        }
        @RenderSection("Scripts", required: false)
    </body>
</html>