Models/AdminCallRequest.cs
namespace Servindustria.Models;

public class AdminCallRequest {
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Company { get; set; }
    public int Phone { get; set; }
    public string? Message { get; set; }
    public DateTime Date { get; set; } = DateTime.Now;
    public bool Seen { get; set; } = false;
}

Models/AdminContactForm.cs
namespace Servindustria.Models;

public class AdminContactForm {
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Company { get; set; }
    public int? Phone { get; set; }
    public string Email { get; set; } = null!;
    public string? Message { get; set; }
    public DateTime Date { get; set; } = DateTime.Now;
    public bool Seen { get; set; } = false;
}

Models/Product.cs
namespace Servindustria.Models {
    public class Product {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int CategoryId { get; set; }
        public ProductCategory? Category { get; set; }
    }
}

Models/TechnicalTable.cs
namespace Servindustria.Models {
    public class TechnicalTableOrCatalog {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}

Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

public class AboutModel : PageModel {
    public void OnGet() {
        
    }

    public void OnPost() {

    }
}

Pages/Admin.cshtml.cs
using Servindustria.Models;
using Servindustria.Data.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;

public class AdminModel : PageModel {
    private readonly IUserRepository _userRepository;
    private readonly ICallRequestRepository _callRequestRepository;

    public AdminModel(IUserRepository userRepository, ICallRequestRepository callRequestRepository) {
        _userRepository = userRepository;
        _callRequestRepository = callRequestRepository;
    }

    public IEnumerable<CallRequest> SeenCallRequests { get; set; } = new List<CallRequest>();
    public IEnumerable<CallRequest> UnseenCallRequests { get; set; } = new List<CallRequest>();

    public int TotalUnseenCallRequests { get; set; }
    public int TotalSeenCallRequests { get; set; }
    
    public int UnseenCallRequestsCurrentPage { get; set; }
    public int SeenCallRequestsCurrentPage { get; set; }
    
    public int PageSize { get; set; } = 2;
    
    public async Task<IActionResult> OnGetAsync(int unseenCallRequestsCurrentPage = 1, int seenCallRequestsCurrentPage = 1) {
        if (User.Identity == null || !User.Identity.IsAuthenticated) return RedirectToPage("/Authentication");
        if (!User.IsInRole("Admin")) return RedirectToPage("/Index");
        
        UnseenCallRequestsCurrentPage = unseenCallRequestsCurrentPage;
        SeenCallRequestsCurrentPage = seenCallRequestsCurrentPage;

        var unseenCallRequests = await _callRequestRepository.GetCallRequestsAsync(UnseenCallRequestsCurrentPage, PageSize, false);
        var seenCallRequests = await _callRequestRepository.GetCallRequestsAsync(SeenCallRequestsCurrentPage, PageSize, true);

        TotalUnseenCallRequests = unseenCallRequests.totalCount;
        TotalSeenCallRequests = seenCallRequests.totalCount;
        SeenCallRequests = seenCallRequests.callRequests;
        UnseenCallRequests = unseenCallRequests.callRequests;
        
        return Page();
}

    public async Task<IActionResult> OnPostSeenUnseenAsync(int id) {
        if (User.Identity == null || !User.Identity.IsAuthenticated) return RedirectToPage("/Authentication");
        if (!User.IsInRole("Admin")) return RedirectToPage("/Index");

        await _callRequestRepository.SetSeenUnseenAsync(id);
        return RedirectToPage("/Admin");
    }

    public IActionResult OnPostPage(int SeenCallRequestsCurrentPage, int UnseenCallRequestsCurrentPage) {
        if (User.Identity == null || !User.Identity.IsAuthenticated) return RedirectToPage("/Authentication");
        if (!User.IsInRole("Admin")) return RedirectToPage("/Index");

        return RedirectToPage("/Admin", new { UnseenCallRequestsCurrentPage, SeenCallRequestsCurrentPage });
    }
}

Pages/AdminManageItems.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Servindustria.Data.Interfaces;
using Servindustria.Models;

namespace Servindustria.Pages
{
    public class ManageItemsModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        private readonly ITechnicalTableOrCatalogRepository _technicalTableRepository;
        private readonly IProductCategoryRepository _productCategoryRepository;

        public ManageItemsModel(IProductRepository productRepository, ITechnicalTableOrCatalogRepository technicalTableRepository, IProductCategoryRepository productCategoryRepository)
        {
            _productRepository = productRepository;
            _technicalTableRepository = technicalTableRepository;
            _productCategoryRepository = productCategoryRepository;
        }

        public IEnumerable<Product> Products { get; set; } = new List<Product>();
        public IEnumerable<TechnicalTableOrCatalog> TechnicalTableOrCatalogs { get; set; } = new List<TechnicalTableOrCatalog>();
        public IEnumerable<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();

        public async Task<IActionResult> OnGetAsync()
        {
            if (User.Identity == null || !User.Identity.IsAuthenticated) return RedirectToPage("/Authentication");
            if (!User.IsInRole("Admin")) return RedirectToPage("/Index");
            Products = await _productRepository.GetAllProductsAsync();
            TechnicalTableOrCatalogs = await _technicalTableRepository.GetTechnicalTableOrCatalogsAsync();
            ProductCategories = await _productCategoryRepository.GetProductCategoriesAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAddProductAsync(Product? Product = null, IFormFile? ImageFile = null, IFormFile? PdfFile = null) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            if (!ModelState.IsValid || Product == null || ImageFile == null || PdfFile == null) return RedirectToPage("/AdminManageItems");


            ProductCategory? category = await _productCategoryRepository.GetProductCategoryByIdAsync(Product.CategoryId);
            if (category == null) return Page();
            Product.Category = category;

            await _productRepository.AddProductAsync(Product);
            var imgPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imgs", "product_" + Product.Id.ToString() + Path.GetExtension(ImageFile.FileName));
            var pdfPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pdfs", "product_" + Product.Id.ToString() + Path.GetExtension(PdfFile.FileName));

            if (ImageFile != null)
            {
                using (var fileStream = new FileStream(imgPath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(fileStream);
                }
            }

            if (PdfFile != null)
            {
                using (var fileStream = new FileStream(pdfPath, FileMode.Create))
                {
                    await PdfFile.CopyToAsync(fileStream);
                }
            }

            TempData["SuccessMessage"] = "Produto adicionado com sucesso.";
            return RedirectToPage("/AdminManageItems");
        }

        public async Task<IActionResult> OnPostAddTechnicalTableOrCatalogAsync(TechnicalTableOrCatalog? TechnicalTableOrCatalog = null, IFormFile? PdfFile = null) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            if (!ModelState.IsValid || TechnicalTableOrCatalog == null || PdfFile == null) return RedirectToPage("/AdminManageItems");

            await _technicalTableRepository.AddTechnicalTableOrCatalogAsync(TechnicalTableOrCatalog);
            var pdfPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pdfs", "technicaltable_" + TechnicalTableOrCatalog.Id.ToString() + Path.GetExtension(PdfFile.FileName));

            if (PdfFile != null)
            {
                using (var fileStream = new FileStream(pdfPath, FileMode.Create))
                {
                    await PdfFile.CopyToAsync(fileStream);
                }
            }

            TempData["SuccessMessage"] = "Tabela técnica adicionada com sucesso.";
            return RedirectToPage("/AdminManageItems");
        }

        public async Task<IActionResult> OnPostDeleteProductAsync(int id) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            await _productRepository.DeleteProductAsync(id);
            
            var imgPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imgs", "product_" + id.ToString() + getProductImageExtension(id));
            var pdfPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pdfs", "product_" + id.ToString() + ".pdf");

            if (System.IO.File.Exists(imgPath)) System.IO.File.Delete(imgPath);
            if (System.IO.File.Exists(pdfPath)) System.IO.File.Delete(pdfPath);

            TempData["SuccessMessage"] = "Produto eliminado com sucesso.";
            return RedirectToPage("/AdminManageItems");
        }

        public async Task<IActionResult> OnPostDeleteTechnicalTableOrCatalogAsync(int id) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            await _technicalTableRepository.DeleteTechnicalTableOrCatalogAsync(id);

            var pdfPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pdfs", "technicaltable_" + id.ToString() + ".pdf");
            if (System.IO.File.Exists(pdfPath)) System.IO.File.Delete(pdfPath);

            TempData["SuccessMessage"] = "Tabela técnica eliminada com sucesso.";
            return RedirectToPage("/AdminManageItems");
        }

        private string getProductImageExtension(int id) {
            foreach (string file in Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imgs"))) {
                string fileName = Path.GetFileName(file);
                if (fileName.StartsWith("product_" + id.ToString())) {
                    return Path.GetExtension(fileName);
                }
            }

            return "";
        }

        public async Task<IActionResult> OnPostAddProductCategoryAsync(ProductCategory? ProductCategory = null) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            if (!ModelState.IsValid || ProductCategory == null) return RedirectToPage("/AdminManageItems");

            await _productCategoryRepository.AddProductCategoryAsync(ProductCategory);
            TempData["SuccessMessage"] = "Categoria de produto adicionada com sucesso.";
            return RedirectToPage("/AdminManageItems");
        }

        public async Task<IActionResult> OnPostDeleteProductCategoryAsync(int id) {
            if (!User.IsInRole("Admin")) return RedirectToPage("/Authentication");
            bool result = await _productCategoryRepository.DeleteProductCategoryAsync(id);
            if (!result) {
                TempData["ErrorMessage"] = "Não pode eliminar uma categoria de produto enquanto houver produtos associados a ela.";
            }
            else {
                TempData["SuccessMessage"] = "Categoria de produto eliminada com sucesso.";
            }
            return RedirectToPage("/AdminManageItems");
        }
    }
}

Pages/Authentication.cshtml.cs
using Servindustria.Models;
using Servindustria.Data.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using System.Globalization;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

public class AuthenticationModel : PageModel {
    private readonly IUserRepository _repository;

    /* REGISTER */
    [FromForm]
    public User? NewUser { get; set; }
    
    [BindProperty]
    public string? ConfirmPassword { get; set; } = "";

    /* LOGIN */
    [BindProperty]
    public string? loginEmail { get; set; } = "";
    
    [BindProperty]
    public string? loginPassword { get; set; } = "";

    public AuthenticationModel(IUserRepository repository) {
        _repository = repository;
    }

    public IActionResult OnGet() {
        if (User.Identity != null && User.Identity.IsAuthenticated) return RedirectToPage("/Index");
        return Page();
    }

    public async Task<IActionResult> OnPostLoginAsync() {
        if (loginEmail == null || loginPassword == null) return new JsonResult(new {success = false, error = "Email e/ou Password incorretos"});

        if (await _repository.LoginAsync(loginEmail, loginPassword)) {
            var Claims = new List<Claim> {
                        new Claim(ClaimTypes.Name, loginEmail),
                        new Claim(ClaimTypes.Role, await _repository.IsAdmin(loginEmail) ? "Admin" : "User")
                    };
            await HttpContext.SignInAsync("AuthCookies", new ClaimsPrincipal(new ClaimsIdentity(Claims, "AuthCookies")));
        
            return new JsonResult(new {success = true});
        } else {
            return new JsonResult(new {success = false, error = "Email ou Password incorretos"});
        }
    }

    public async Task<IActionResult> OnPostRegisterAsync() {
        if (NewUser == null) return new JsonResult(new {success = false, errors = "Unknown Error"});

        if (await _repository.EmailExistsAsync(NewUser.Email)) ModelState.AddModelError("Email", "Já existe um utilizador com este email");
        if (NewUser.Nif.HasValue)
            if (await _repository.NifExistsAsync(NewUser.Nif.Value))
                ModelState.AddModelError("Nif", "Já existe um utilizador com este NIF");
        
        if (!IsValidEmail(NewUser.Email)) ModelState.AddModelError("Email", "O email não é válido");
        if (NewUser.Password != ConfirmPassword) ModelState.AddModelError("Password", "As passwords não coincidem");
        
        if (NewUser.Nif.HasValue) {
            int nifLength = Math.Abs(NewUser.Nif.Value).ToString().Length;
            if (NewUser.Nif == 0) nifLength = 0;
            if (nifLength != 9 && nifLength != 0) ModelState.AddModelError("Nif", "O NIF deve ter 9 dígitos");
        }
        
        if (NewUser.Phone.HasValue) {
            int phoneLength = Math.Abs(NewUser.Phone.Value).ToString().Length;
            if (NewUser.Phone == 0) phoneLength = 0;
                if (phoneLength != 9 && phoneLength != 0) ModelState.AddModelError("Phone", "O número de telefone / telemóvel deve ter 9 dígitos");
        }
        
        var modelErrors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
        if (modelErrors.Count > 0) return new JsonResult(new {success = false, errors = modelErrors});

        var Claims = new List<Claim> {
            new Claim(ClaimTypes.Name, NewUser.Email),
            new Claim(ClaimTypes.Role, await _repository.IsAdmin(NewUser.Email) ? "Admin" : "User")
        };
        await HttpContext.SignInAsync("AuthCookies", new ClaimsPrincipal(new ClaimsIdentity(Claims, "AuthCookies")));
        
        NewUser.Password = BCrypt.Net.BCrypt.HashPassword(NewUser.Password);

        await _repository.AddUserAsync(NewUser);
        return new JsonResult(new {success = true});        
    }

    private bool IsValidEmail(string email) {
        if (string.IsNullOrWhiteSpace(email)) return false;

        try {
            email = Regex.Replace(email, @"(@)(.+)$", DomainMapper, RegexOptions.None, TimeSpan.FromMilliseconds(200));

            string DomainMapper(Match match) {
                var idn = new IdnMapping();
                string domainName = idn.GetAscii(match.Groups[2].Value);
                return match.Groups[1].Value + domainName;
            }
        } catch (RegexMatchTimeoutException) {
            return false;
        } catch (ArgumentException) {
            return false;
        }

        try {
            return Regex.IsMatch(email,
                @"^[^@\s]+@[^@\s]+\.[^@\s]+$",
                RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(250));
        } catch (RegexMatchTimeoutException) {
            return false;
        }
    }
    
    public async Task<IActionResult> OnPostLogoutAsync() {
        await HttpContext.SignOutAsync("AuthCookies");
        return new JsonResult(new {success = true});
    }
}

Pages/TechnicalTablesAndCatalogs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Servindustria.Data.Interfaces;
using Servindustria.Models;

public class TechnicalTableOrCatalogsModel : PageModel {
    public ITechnicalTableOrCatalogRepository _technicalTable;

    public IEnumerable<TechnicalTableOrCatalog> TechnicalTableOrCatalogs = new List<TechnicalTableOrCatalog>();

    public TechnicalTableOrCatalogsModel(ITechnicalTableOrCatalogRepository technicalTable)
    {
        _technicalTable = technicalTable;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        TechnicalTableOrCatalogs = await _technicalTable.GetTechnicalTableOrCatalogsAsync();
        return Page();
    }
}

Pages/Admin.cshtml
@page "/admin/{UnseenCallRequestsCurrentPage?}/{SeenCallRequestsCurrentPage?}"
@model AdminModel

<link rel="stylesheet" href="~/css/admin.css" asp-append-version="true">
<div class="bigContainer">
    <div class="callRequestContainer">
        <h1>Pedidos de Contacto Não Vistos</h1>

        @if (Model.UnseenCallRequests.Count() == 0)
        {
            <br>
            <p>Já viu todos os pedidos de contacto!</p>
        }

        @foreach (var item in Model.UnseenCallRequests)
        {
            <div class="callRequest">
                <p>Nome: @item.Name</p>
                @if (item.Company != null)
                {
                    <p>Empresa: @item.Company</p>
                }
                <p>Telefone: @item.Phone</p>
                @if (item.Message != null) {
                    <p>Mensagem: @item.Message</p>
                }
                <p>Data: @item.Date.ToString("dd-MM-yyyy HH:mm:ss")</p>

                <form method="post" asp-page="/Admin" asp-page-handler="SeenUnseen">
                    <input type="hidden" name="id" value="@item.Id" />
                    <input type="submit" value="Visto" />
                </form>
            </div>
        }

        <div class="pagination">
            <form method="post" asp-page="/Admin" asp-page-handler="Page">
                <input type="hidden" name="UnseenCallRequestsCurrentPage" value="@(Model.UnseenCallRequestsCurrentPage - 1)" />
                <input type="hidden" name="SeenCallRequestsCurrentPage" value="@(Model.SeenCallRequestsCurrentPage - 1)" />
                <input class="@(Model.UnseenCallRequestsCurrentPage <= 1 ? "invisible-btn" : "")" type="submit" value="<" />
            </form>

            <span>Página @Model.UnseenCallRequestsCurrentPage</span>

            <form method="post" asp-page="/Admin" asp-page-handler="Page">
                <input type="hidden" name="UnseenCallRequestsCurrentPage" value="@(Model.UnseenCallRequestsCurrentPage + 1)" />
                <input type="hidden" name="SeenCallRequestsCurrentPage" value="@(Model.SeenCallRequestsCurrentPage + 1)" />
                <input class="page-btn @(Model.UnseenCallRequestsCurrentPage * Model.PageSize >= Model.TotalUnseenCallRequests ? "invisible-btn" : "")" type="submit" value=">" />
            </form>
        </div>
    </div>

    <div class="callRequestContainer">
        <h1>Pedidos de Contacto Vistos</h1>

        @if (Model.SeenCallRequests.Count() == 0)
        {
            <br>
            <p>Não existem pedidos de contacto vistos.</p>
        }

        @foreach (var item in Model.SeenCallRequests)
        {
            <div class="callRequest">
                <p>Nome: @item.Name</p>
                @if (item.Company != null)
                {
                    <p>Empresa: @item.Company</p>
                }
                <p>Telefone: @item.Phone</p>
                @if (item.Message != null) {
                    <p>Mensagem: @item.Message</p>
                }
                <p>Data: @item.Date.ToString("dd-MM-yyyy HH:mm:ss")</p>

                <form method="post" asp-page="/Admin" asp-page-handler="SeenUnseen">
                    <input type="hidden" name="id" value="@item.Id" />
                    <input type="submit" value="Não Visto" />
                </form>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
}

Pages/AdminManageItems.cshtml
@page "/admin/gerirItems"
@model ManageItemsModel

@if(TempData["SuccessMessage"] != null)
{
    <div class="success" style="display: flex; margin-top: 50px; width: fit-content; margin-left: auto; margin-right: auto;">
        @TempData["SuccessMessage"]
    </div>
}

@if(TempData["ErrorMessage"] != null)
{
    <div class="error" style="display: flex; margin-top: 50px; width: fit-content; margin-left: auto; margin-right: auto;">
        @TempData["ErrorMessage"]
    </div>
}

<div class="bigContainer">
    <div class="smallContainer">
        <h1>Remover Produto</h1>

        <form asp-page="AdminManageItems" asp-page-handler="DeleteProduct" method="post">
            <div class="smallContainerEntry">
                <select name="id" required>
                    <option value="" disabled selected>Produto</option>
                    @foreach (var product in Model.Products) {
                        <option value="@product.Id">@product.Name</option>
                    }
                </select>
            </div>

            <input type="submit" value="Remover" />
        </form>
    </div>

    <div class="smallContainer">
        <h1>Remover Tabela / Catálogo</h1>

        <form asp-page="AdminManageItems" asp-page-handler="DeleteTechnicalTableOrCatalog" method="post">
            <div class="smallContainerEntry">
                <select name="id" required>
                    <option value="" disabled selected>Tabela Técnica / Catálogo</option>
                    @foreach (var technicalTable in Model.TechnicalTableOrCatalogs) {
                        <option value="@technicalTable.Id">@technicalTable.Name</option>
                    }
                </select>
            </div>

            <input type="submit" value="Remover" />
        </form>
    </div>

    <div class="smallContainer">
        <h1>Remover Categoria</h1>

        <form asp-page="AdminManageItems" asp-page-handler="DeleteProductCategory" method="post">
            <div class="smallContainerEntry">
                <select name="id" required>
                    <option value="" disabled selected>Categoria</option>
                    @foreach (var category in Model.ProductCategories) {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>

            <input type="submit" value="Remover" />
        </form>
    </div>
</div>

<div class="bigContainer">
    <div class="smallContainer">
        <h1>Adicionar Produto</h1>

        <form asp-page="AdminManageItems" asp-page-handler="AddProduct" method="post" enctype="multipart/form-data">
            <div class="smallContainerEntry">
                <input type="text" name="Name" placeholder="Nome do Produto" required/>
            </div>
            <div class="smallContainerEntry">
                <select name="CategoryId" required>
                    <option value="" disabled selected>Categoria</option>
                    @foreach (var category in Model.ProductCategories) {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
            <div class="smallContainerEntry">
                <h2>Imagem</h2>
                <input type="file" name="ImageFile" accept="image/*" placeholder="Imagem" required/>
            </div>
            <div class="smallContainerEntry">
                <h2>PDF</h2>
                <input type="file" name="PdfFile" accept=".pdf" placeholder="PDF" required/>
            </div>

            <input type="submit" value="Adicionar" />
        </form>
    </div>

    <div class="smallContainer">
        <h1>Adicionar Tabela / Catálogo</h1>
        
        <form asp-page="AdminManageItems" asp-page-handler="AddTechnicalTableOrCatalog" method="post" enctype="multipart/form-data">
            <div class="smallContainerEntry">
                <input type="text" name="Name" placeholder="Nome da Tabela / Catálogo" required/>
            </div>
            <div class="smallContainerEntry">
                <input type="file" name="PdfFile" accept=".pdf" placeholder="PDF" required/>
            </div>

            <input type="submit" value="Adicionar" />
        </form>
    </div>

    <div class="smallContainer">
        <h1>Adicionar Categoria</h1>

        <form asp-page="AdminManageItems" asp-page-handler="AddProductCategory" method="post">
            <div class="smallContainerEntry">
                <input type="text" name="Name" placeholder="Nome da Categoria" required/>
            </div>

            <input type="submit" value="Adicionar" />
        </form>
    </div>
</div>

Pages/Authentication.cshtml
@page "/autenticacao"
@model AuthenticationModel

<link rel="stylesheet" href="~/css/authentication.css" asp-append-version="true">

<div id="authentication">
    <form id="login-form" class="formClass" method="post" asp-page="/Authentication" asp-page-handler="Login">
        @Html.AntiForgeryToken()
        <p>Já tem conta? Faça login!</p>
        <div id="login-error" class="error"></div>
        <div id="login-success" class="success"></div>
        <input type="text" name="loginEmail" placeholder="Email" />
        <input type="password" name="loginPassword" placeholder="Password" />
        
        <input type="submit" value="Login"/>
    </form>

    <form id="register-form" class="formClass" method="post" asp-page="/Authentication" asp-page-handler="Register">
        @Html.AntiForgeryToken()
        <p>Ainda não tem conta? Registe-se!</p>
        <div id="register-error" class="error"></div>
        <div id="register-success" class="success"></div>
        <input type="text" name="Name" placeholder="Nome" required/>
        <input type="text" name="Company" placeholder="Empresa"/>
        <input type="text" name="Address" placeholder="Morada"/>
        <input type="number" name="Nif" placeholder="NIF"/>
        <input type="number" name="Phone" placeholder="Telefone / Telemóvel"/>
        <input type="text" name="Email" placeholder="Email" required/>
        <input type="password" name="Password" placeholder="Password" required/>
        <input type="password" name="ConfirmPassword" placeholder="Confirmação da Password" required/>
        
        <input type="submit" value="Registar"/>
    </form>
</div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/authentication.js"></script>
}

Pages/Index.cshtml
@page "/"

<link rel="stylesheet" href="~/css/index.css" asp-append-version="true">

<h1>Bem-vindo/a à Servindustria!</h1>
<h2>Importação / Revenda / Comércio</h2>

<div class="content">
    <div class="left-content">
        <p>Somos uma Empresa sediada em Barcelos e que se dedica à Importação, Revenda e Comércio de todo o tipo de Produtos, Acessórios e Equipamentos Industriais.</p>
        <p>Oferecemos todo o tipo de soluções multimarcas e para toda as áreas da indústria nacional. </p>
        <p>O nosso objetivo é a plena satisfação das necessidades dos nossos clientes.</p>
    </div>
    
    <div class="logo">
        <img src="~/imgs/favicon.png" alt="Logótipo - Servindustria">
    </div>

    <div class="right-content">
        <p>Válvulas / Bombas / Acessórios Têxteis / Confecção / Tinturaria / Estamparia</p>
        <p>Acabamento / Auto-Hidráulica / Etas e Etares / AVAC / Climatização</p>
        <p>Águas / Saneamento / Equipamentos Sanitários</p>
        <p>Construção Civil / Obras Públicas / Petrolífera</p>
        <p>Naval / Papeleira / Farmacêutica</p>
    </div>
</div>